services:
  - type: web
    name: ab-optimizer-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node scripts/test-db.js && npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        sync: false
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
      - key: SCOPES
        sync: false 